### ISSUE TITLE
[Q] How to change the used keyserver?

### ISSUE THREAD

**Issue by ikarisan** [landsh-de/GpgTools#1]
Hi!

At first, thank you very very much for your work and to make my life easier to install VS-NfD complienced Gpg4Win installations.

But can you tell what to do / to change so that I am able to use an alternative gpg keyserver? I am using Gpg4Win within an isolated network that has an own keyserver running. So I tried to set "keyserver hkp://myownkeyserver.local.domain" in gpg.conf. This server is shown on the "Directory Services" page of Kleopatra but not on "GnuPG system / Net". And gpg still tries to use "hkp://pgpkeys.eu:11371" :(

**Comment by vitusb** [comment]
Hello,
sorry for my late reply, I was busy in another project...

> ... can you tell what to do / to change ...

Okay, here we go ...

The VS-NfD compilance means also a central hardened configuration for ALL users, logged into the system in order to guarantee a hardened config, because with default-values GnuPG will use mostly weak values for some attributes.

The central config resides in the directory **(you have to be a user with admin rights in order to change some stuff here)**:
`%SYSTEMDRIVE%\ProgramData\GNU\etc\gnupg\`

Here we have the config-file:
`%SYSTEMDRIVE%\ProgramData\GNU\etc\gnupg\dirmngr.conf`

The newer versions of these files are using a consolidated configuration-scheme, that respects also Registry-Values from Windows. I'm strictly **NOT USING** Regsitry-Values, because of their incompatibility to UNIX (Linux) and because of their complicated handling by installers during uninstall, etc. and because they're complicating the whole configuration.

For the keyserver, the responsible sequence in "dirmngr.conf`" is:
```
[force]

[getreg kname HKLM\Software\GNU\GnuPG:NtdsKeyserver]
[getreg kname2 HKLM\Software\GNU\GnuPG:Keyserver]
[if $kname]
  keyserver ldap://$kname/????gpgNtds=1
  [let kname2]
[fi]
[if $kname2]
   keyserver $kname2
   [let kname done]
[fi]
[if $kname -z]
    # keyserver ldap:///
    keyserver hkp://pgpkeys.eu:11371
[fi]

[-force]
```

So because I'm not using Registry-Values, "$kname" is zero and the sequence **[if $kname -z]** will do the trick ...

Change ...
```
    # keyserver ldap:///
    keyserver hkp://pgpkeys.eu:11371
```
to
```
    # keyserver ldap:///
    keyserver [MY-OWN-KEYSERVER-URL]
```

By the way ...
The new configuration-scheme was borrowed from "GnuPG VS Desktop" in order to be compatible with this package :smiley:
